#!/bin/bash

set -e

to_run=$(echo "$PATH" | tr ':' '\n' | sort -u | xargs -I{} find {} -type f -executable -printf '%f\n' | sort -u | fzf --prompt "run: ")
[[ -z "$to_run" ]] && exit 1
setsid "$to_run" >/dev/null 2>&1 &
sleep 0.5

