#!/bin/bash

all_pages=$(man -k .)
chosen_page=$(echo "$all_pages" | fzf)

[ -z "$chosen_page" ] && exit 1

name=$(echo "$chosen_page" | sed -E 's/^([^(]+) \(([0-9a-z]+)\).*/\1/')
section=$(echo "$chosen_page" | sed -E 's/^([^(]+) \(([0-9a-z]+)\).*/\2/')

man "$section" "$name"
