#!/bin/bash

# https://github.com/porras/dmenu-emoji/blob/master/dmenu-emoji.sh
all_emojis="$HOME/.local/share/emojis.txt"
emoji=$(cat "$all_emojis" | fzf --prompt 'emoji: ' --preview 'echo {} | awk "{print \$NF}"' --preview-window 'up:1' | awk '{printf $NF}')
[[ -z "$emoji" ]] && exit 1

if [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
    clipboard="wl-copy"
elif [[ "$XDG_SESSION_TYPE" == "x11" || -n "$DISPLAY" ]]; then
    clipboard="xclip -selection clipboard"
else
    echo "Couldn't determin clipboard tool. XDG_SESSION_TYPE is not set to wayland or x11"
    exit 1
fi

echo "$emoji" | "$clipboard"
