;;; app-launcher-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from app-launcher.el

(autoload 'app-launcher-run-app "app-launcher" "\
Launch an application installed on your machine.
When ARG is non-nil, ignore NoDisplay property in *.desktop files.

(fn &optional ARG)" t)
(register-definition-prefixes "app-launcher" '("app-launcher-"))

;;; End of scraped data

(provide 'app-launcher-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; app-launcher-autoloads.el ends here
