set -g focus-events on
set -g allow-passthrough on
set -s copy-command 'wl-copy'
# set -g popup-border-lines rounded

set -g default-terminal "xterm-256color"
set -as terminal-overrides ',xterm-256color:RGB'

set -g extended-keys always
set -as terminal-features 'xterm*:extkeys'   

set-option -g status-position top
set -g status-right ''
# set -g status-right "#{?#{==:#{pane_current_command},nvim},#[fg=#1d2021]#[bg=#adb024]  #[fg=#ebdbb2]#[bg=#3c3836] #{@nvim_file},#[fg=#ebdbb2]#[bg=#3c3836] #{pane_current_path}} "

set -g base-index 1
setw -g pane-base-index 1

# Transparent status bar
set -g status-style bg=default,fg=colour223
set -g pane-border-style fg=default
# set -g pane-active-border-style fg=default

set -g status-left '#[fg=colour178,bold]#S#[fg=colour178,bold]: '
set -g status-left-length 50
set -g window-status-format '#I:#W'
# set -g window-status-current-format '#[fg=red,bold]#I:#W#[none]'
set -g window-status-current-format '#[fg=red,bold]#I:#W#{?window_zoomed_flag,[M],}#[none]'


##################################################
## keymaps
##################################################
# set preix key
unbind C-b
set -g prefix M-space

# Use Vim-like keybindings for resizing
bind -r k resize-pane -U 5
bind -r j resize-pane -D 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5

# maximize pane toggle
bind -r m resize-pane -Z

set -g mouse on
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

unbind s
bind s display-popup -E -w 100% -h 100% -d '#{pane_current_path}' '
session=$(tmux ls -F "#{session_name}: #{session_windows} windows (#{session_path})" 2>/dev/null \
          | fzf --prompt="session: "                                                             \
                --preview="echo {} | cut -d: -f1 | xargs -I {} tmux capture-pane -epJ -t {}"     \
          | cut -d: -f1)
[ -z "$session" ] && exit 0
tmux switch-client -t "$session"   
'

unbind w
bind w display-popup -E -w 100% -h 100% -d '#{pane_current_path}' '
window_id=$(tmux list-windows -F "#{window_id} #{window_index}: #{window_name} (#{pane_current_path})" \
            | fzf --prompt="window: "                                                                  \
                  --delimiter=" "                                                                      \
                  --with-nth=2..                                                                       \
                  --preview="tmux capture-pane -ept {1} -S -200"                                       \
            | cut -d" " -f1)
[ -z "$window_id" ] && exit 0
tmux select-window -t "$window_id"
'

# unbind g
# bind g display-popup -E -w 100% -h 100% -d '#{pane_current_path}' 'lazygit'

# # when nvim 'tpipeline' plugin's enabled
# set -g status-left-length 99
# set -g status-right-length 99
# set -g status-justify absolute-centre

##################################################
## plugins
##################################################
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'christoomey/vim-tmux-navigator'

# set -g @plugin 'egel/tmux-gruvbox'
# set -g @tmux-gruvbox 'dark256'
# set -g @tmux-gruvbox-statusbar-alpha 'true'
# set -g @tmux-gruvbox-right-status-x ''
# set -g @tmux-gruvbox-right-status-y ''

# set -g @plugin 'jimeh/tmux-themepack'
# set -g @themepack 'basic'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
