#!/bin/bash

DMENU="dmenu -i -l 20"
DMENU="rofi -dmenu -i"
DMENU="wofi --dmenu -i"

options="logout suspend lockscreen poweroff reboot"
chosen=$(echo $options | tr ' ' '\n' | $DMENU -p "Power Menu")

case ${chosen} in
    logout) kill -9 -1 ;;
    lockscreen) hyprlock ;;
    # lockscreen) swaylock-fancy ;;
    # lockscreen) i3lock ;;
    suspend) systemctl suspend ;;
    poweroff) systemctl poweroff ;;
    reboot) systemctl reboot ;;
esac
