#!/bin/sh

DMENU="dmenu -i -l 20"
DMENU="rofi -dmenu -i"
# DMENU="wofi --dmenu -i"
DMENU="fuzzel -d"

options="logout suspend lockscreen poweroff reboot"
chosen=$(echo $options | tr " " "\n" | $DMENU)

case $chosen in
    logout) kill -9 -1 ;;
    lockscreen) hyprlock ;;
    suspend) systemctl suspend ;;
    poweroff) systemctl poweroff ;;
    reboot) systemctl reboot ;;
esac
