theme = "gruvbox_dark_hard_transparent"

[editor]
line-number = "relative"
bufferline = "never"
gutters = ["line-numbers", "spacer", "diff"]
true-color = true

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.cursor-shape]
insert = "bar"
# insert = "block"

[editor.file-picker]
hidden = false
ignore = false
git-ignore = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
A-j = "copy_selection_on_next_line"
A-k = "copy_selection_on_prev_line"

[keys.normal.space]
t = "@<space>/TODO"
